# .github/workflows/deploy.yml

name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /var/www/ai-data-cleaner

            # --- THE FIX for conflicting changes ---
            # Discard any local changes on the server to ensure a clean pull
            echo "--- 1. Resetting local changes on server ---"
            git reset --hard origin/main

            # Pull the latest code from GitHub
            echo "--- 2. Pulling latest code ---"
            git pull origin main

            # --- Add a check to see the files AFTER the pull ---
            echo "--- 3. Verifying directory contents ---"
            ls -la static/images/

            # Activate the virtual environment
            source env/bin/activate

            # Install dependencies
            echo "--- 4. Installing dependencies ---"
            pip install -r requirements.txt

            # Run Django management commands
            echo "--- 5. Running Django commands ---"
            python manage.py migrate
            python manage.py collectstatic --no-input

            # Restart the Gunicorn service (this will now work without a password)
            echo "--- 6. Restarting application server ---"
            sudo systemctl restart gunicorn.service

            echo "--- DEPLOYMENT COMPLETE ---"