# .github/workflows/deploy.yml

name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the OUTER project directory first
            cd /var/www/ai-data-cleaner

            # Forcefully reset to the latest version from GitHub to avoid conflicts
            echo "--- 1. Resetting local changes on server ---"
            # We must cd into the inner git repo to run git commands
            cd ai-data-cleaner && git reset --hard origin/main && git pull origin main && cd ..

            # --- THE FIX: Activate the virtual environment from the outer directory ---
            echo "--- 2. Activating virtual environment ---"
            source env/bin/activate

            # --- THE FIX: Navigate into the INNER directory before running commands ---
            cd ai-data-cleaner
            echo "--- 3. Now inside $(pwd) ---"
            
            # Now we are in the correct directory, so these commands will work
            echo "--- 4. Installing dependencies ---"
            pip install -r requirements.txt

            echo "--- 5. Running Django commands ---"
            python manage.py migrate
            python manage.py collectstatic --no-input

            # Restart the Gunicorn service
            echo "--- 6. Restarting application server ---"
            sudo systemctl restart gunicorn.service

            echo "--- DEPLOYMENT COMPLETE ---"